# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: GitHub Action for npx

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: mikeal/npx@1.0.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3, JS-DevTools/npm-publish@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npx create-react-app antd-demo-ts --template typescript
    - run: cd antd-demo-ts
    - run: npm start
